GET http://localhost:3003/api/havainnot/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJpZCI6IjYyNGMxM2M2N2M5Yzg5YTIxYjRiYzBiMSIsImlhdCI6MTY0OTE1NDAzM30.2hT6oEsWw_wP_Ohw9jytazkDsca3ep5Dv1wMeiAvEQw