PUT http://localhost:3003/api/havainnot/624c017a68b4259af8b77f4c
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFiYyIsImlkIjoiNjI0YmY2ZjRkYmU0OTZhODgwNWUzZTQ2IiwiaWF0IjoxNjQ5MTQ4Nzk2fQ.SPPfV9IECZ7xKn-M1ahWKZtFSNcEU_sCYwNULhLN-mA

  {
    "laji": "Korppi",
    "paikka": "Alajärvi",
    "paiva": "2022/3/10",
    "aika": "16:05",
    "maara": 1,
    "kommentit": "Lumi sadetta"
  }